name: Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.7"
          cache: true
      - uses: oberhauser-dev/flutter-release-action@v0
        with:
          app-name: 'KzShortner'
          app-version: ${{ github.ref_name }}
          tag: ${{ github.ref }}
          release-type: 'apk'
          token: ${{ github.token }}
